### ISSUE TITLE
APM try to install the version 1.7.0 while it is not yet available

### ISSUE THREAD

**Issue by edaubert** [colameo/io.github.jhipster.jdl.atom#1]
When I opened this issue, the last commit was b71c74a86a947140919039b2b64281df39c44efd

I guess when preparing the version 1.7.0 something went wrong but this version is now proposed on https://atom.io/packages/ide-jhipster

Moreover the apm command try to install it while it is not available

**Comment by colameo** [comment]
Yes, I'm aware about this issue - it happened during the preparation of the new release 1.7.0.

However, I will publish a new version soon. In the meantime you may want to switch to VS Code or Eclipse?

**Comment by colameo** [comment]
ok, I've built a new version (1.7.1) which works now.

closing this issue. please reopen if problem persists.
